//----------------------------------------------------------------------------------------------------------------------
/// @file AppProvenanceTests.cpp
/// @brief Verifies source attribution and persistence distinctions for editor subjects.
//----------------------------------------------------------------------------------------------------------------------
#include "App/Model/Workspace/Provenance.h"

#include <catch2/catch_test_macros.hpp>

#include <string>
#include <string_view>

using namespace lmx::app;

//======================================================================================================================
TEST_CASE("authored document and subject values need no provenance mark", "[app][provenance]") {
    REQUIRE_FALSE(documentProvenance(false, "Assets/Scenes/sponza.scene.gltf"));
    REQUIRE_FALSE(subjectProvenance(std::nullopt, std::nullopt, false));
    REQUIRE_FALSE(resolutionProvenance(false, 0.75f, 16.67f));
}

//======================================================================================================================
TEST_CASE("dirty document provenance names the operator and loaded path", "[app][provenance]") {
    std::string path = "Assets/Scenes/material-lab.scene.gltf";
    const auto mark = documentProvenance(true, path);
    REQUIRE(mark);
    REQUIRE(mark->kind == Provenance::Edited);
    REQUIRE(mark->actor == Actor::Operator);
    path.assign("replacement.scene.gltf");
    REQUIRE(mark->source.find("Assets/Scenes/material-lab.scene.gltf") != std::string::npos);
}

//======================================================================================================================
TEST_CASE("generated subject provenance names its lab and unsaved lifetime", "[app][provenance]") {
    std::string lab = "VisibilityLab";
    const auto mark = subjectProvenance(lab, std::nullopt, false);
    REQUIRE(mark);
    REQUIRE(mark->kind == Provenance::SessionOnly);
    REQUIRE(mark->actor == Actor::System);
    lab.clear();
    REQUIRE(mark->source == "Generated by VisibilityLab · not saved");
}

//======================================================================================================================
TEST_CASE("CLI masks keep their exact flag in session provenance", "[app][provenance]") {
    std::string flag = "--local-light-rig off";
    const auto mark = subjectProvenance(std::nullopt, flag, false);
    REQUIRE(mark);
    REQUIRE(mark->kind == Provenance::SessionOnly);
    REQUIRE(mark->actor == Actor::Operator);
    flag.clear();
    REQUIRE(mark->source.find("--local-light-rig off") != std::string::npos);
    REQUIRE(mark->source.find("not saved") != std::string::npos);
}

//======================================================================================================================
TEST_CASE("operator edits of authored subjects are edited provenance", "[app][provenance]") {
    const auto mark = subjectProvenance(std::nullopt, std::nullopt, true);
    REQUIRE(mark);
    REQUIRE(mark->kind == Provenance::Edited);
    REQUIRE(mark->actor == Actor::Operator);
    REQUIRE_FALSE(mark->source.empty());
}

//======================================================================================================================
TEST_CASE("edits cannot make generated or CLI masked subjects authored", "[app][provenance]") {
    for (const auto& mark : {subjectProvenance("LightLab", std::nullopt, true),
                             subjectProvenance(std::nullopt, "--visibility off", true),
                             subjectProvenance("LightLab", "--local-lights off", true)}) {
        REQUIRE(mark);
        REQUIRE(mark->kind == Provenance::SessionOnly);
        REQUIRE(mark->actor == Actor::Operator);
        REQUIRE(mark->source.find("not saved") != std::string::npos);
        REQUIRE(mark->source.find("edited by operator") != std::string::npos);
    }
    const auto combined = subjectProvenance("LightLab", "--local-lights off", false);
    REQUIRE(combined);
    REQUIRE(combined->kind == Provenance::SessionOnly);
    REQUIRE(combined->actor == Actor::Operator);
    REQUIRE(combined->source.find("Generated by LightLab") != std::string::npos);
    REQUIRE(combined->source.find("--local-lights off") != std::string::npos);
}

//======================================================================================================================
TEST_CASE("controller provenance identifies the policy scale and millisecond budget",
          "[app][provenance]") {
    const auto mark = resolutionProvenance(true, 0.75f, 16.67f);
    REQUIRE(mark);
    REQUIRE(mark->kind == Provenance::SystemApplied);
    REQUIRE(mark->actor == Actor::System);
    REQUIRE(mark->source.find("Dynamic resolution") != std::string::npos);
    REQUIRE(mark->source.find("0.750") != std::string::npos);
    REQUIRE(mark->source.find("16.67 ms") != std::string::npos);
    REQUIRE(resolutionProvenance(true, 1.0f, 8.0f));
}

//======================================================================================================================
TEST_CASE("row tooltips state the generator sentence exactly once", "[app][provenance]") {
    const std::string sentence = "Generated by LightLab · not saved";
    const auto count = [&](const std::string& text) {
        size_t found = 0;
        for (size_t at = text.find(sentence); at != std::string::npos;
             at = text.find(sentence, at + 1))
            ++found;
        return found;
    };
    auto mark = subjectProvenance("LightLab", "--local-lights off", true);
    REQUIRE(mark);
    mark->source += " · Assets/Scenes/light-lab.scene.gltf";
    const auto marked = rowProvenanceTooltip("LightLab", mark);
    REQUIRE(count(marked) == 1);
    REQUIRE(marked == mark->source);
    REQUIRE(marked.find("CLI mask --local-lights off") != std::string::npos);
    REQUIRE(marked.find("edited by operator") != std::string::npos);
    REQUIRE(marked.find("Assets/Scenes/light-lab.scene.gltf") != std::string::npos);
    REQUIRE(rowProvenanceTooltip("LightLab", std::nullopt) == sentence);
}

//======================================================================================================================
TEST_CASE("row tooltips keep the generator beside a mark that does not name it",
          "[app][provenance]") {
    const auto mark = subjectProvenance(std::nullopt, "--local-light-rig off", false);
    REQUIRE(mark);
    REQUIRE(rowProvenanceTooltip("LightLab", mark) ==
            "Generated by LightLab · not saved\n" + mark->source);
    REQUIRE(rowProvenanceTooltip(std::nullopt, mark) == mark->source);
    REQUIRE(rowProvenanceTooltip(std::nullopt, std::nullopt).empty());
}
