//----------------------------------------------------------------------------------------------------------------------
/// @file EditorThemeTokens.cpp
/// @brief Defines generated byte-exact editor colors and slot mappings.
//----------------------------------------------------------------------------------------------------------------------
#include "EditorThemeTokens.h"

namespace lmx::app {

// clang-format off
const ThemePalette kDarkPalette = {{
    {5.0f / 255.0f, 6.0f / 255.0f, 7.0f / 255.0f, 1.0f}, // surface/canvas
    {21.0f / 255.0f, 22.0f / 255.0f, 24.0f / 255.0f, 1.0f}, // surface/panel
    {26.0f / 255.0f, 28.0f / 255.0f, 30.0f / 255.0f, 1.0f}, // surface/raised
    {11.0f / 255.0f, 12.0f / 255.0f, 14.0f / 255.0f, 1.0f}, // surface/sunken
    {35.0f / 255.0f, 36.0f / 255.0f, 38.0f / 255.0f, 1.0f}, // surface/hover
    {44.0f / 255.0f, 46.0f / 255.0f, 48.0f / 255.0f, 1.0f}, // surface/active
    {5.0f / 255.0f, 6.0f / 255.0f, 7.0f / 255.0f, 0.86f}, // surface/overlay
    {11.0f / 255.0f, 12.0f / 255.0f, 14.0f / 255.0f, 1.0f}, // surface/viewport
    {248.0f / 255.0f, 250.0f / 255.0f, 253.0f / 255.0f, 1.0f}, // text/primary
    {163.0f / 255.0f, 165.0f / 255.0f, 167.0f / 255.0f, 1.0f}, // text/secondary
    {103.0f / 255.0f, 105.0f / 255.0f, 107.0f / 255.0f, 1.0f}, // text/disabled
    {5.0f / 255.0f, 6.0f / 255.0f, 7.0f / 255.0f, 1.0f}, // text/on-accent
    {35.0f / 255.0f, 36.0f / 255.0f, 38.0f / 255.0f, 1.0f}, // border/subtle
    {103.0f / 255.0f, 105.0f / 255.0f, 107.0f / 255.0f, 1.0f}, // border/strong
    {76.0f / 255.0f, 171.0f / 255.0f, 253.0f / 255.0f, 1.0f}, // border/focus
    {76.0f / 255.0f, 171.0f / 255.0f, 253.0f / 255.0f, 1.0f}, // accent/operator
    {135.0f / 255.0f, 196.0f / 255.0f, 253.0f / 255.0f, 1.0f}, // accent/operator-hover
    {180.0f / 255.0f, 217.0f / 255.0f, 253.0f / 255.0f, 1.0f}, // accent/operator-active
    {135.0f / 255.0f, 196.0f / 255.0f, 253.0f / 255.0f, 1.0f}, // accent/operator-text
    {76.0f / 255.0f, 171.0f / 255.0f, 253.0f / 255.0f, 0.18f}, // accent/operator-subtle
    {184.0f / 255.0f, 138.0f / 255.0f, 247.0f / 255.0f, 1.0f}, // AccentAgent
    {204.0f / 255.0f, 171.0f / 255.0f, 253.0f / 255.0f, 1.0f}, // AccentAgentHover
    {221.0f / 255.0f, 202.0f / 255.0f, 253.0f / 255.0f, 1.0f}, // AccentAgentActive
    {204.0f / 255.0f, 171.0f / 255.0f, 253.0f / 255.0f, 1.0f}, // AccentAgentText
    {184.0f / 255.0f, 138.0f / 255.0f, 247.0f / 255.0f, 0.18f}, // AccentAgentSubtle
    {94.0f / 255.0f, 188.0f / 255.0f, 123.0f / 255.0f, 1.0f}, // status/success
    {212.0f / 255.0f, 152.0f / 255.0f, 36.0f / 255.0f, 1.0f}, // status/warning
    {249.0f / 255.0f, 119.0f / 255.0f, 114.0f / 255.0f, 1.0f}, // status/error
    {163.0f / 255.0f, 165.0f / 255.0f, 167.0f / 255.0f, 1.0f}, // status/info
    {76.0f / 255.0f, 171.0f / 255.0f, 253.0f / 255.0f, 1.0f}, // actor/operator
    {184.0f / 255.0f, 138.0f / 255.0f, 247.0f / 255.0f, 1.0f}, // ActorAgent
    {132.0f / 255.0f, 134.0f / 255.0f, 136.0f / 255.0f, 1.0f}, // actor/system
    {212.0f / 255.0f, 152.0f / 255.0f, 36.0f / 255.0f, 1.0f}, // prov/session
    {76.0f / 255.0f, 171.0f / 255.0f, 253.0f / 255.0f, 0.28f}, // selection/bg
    {248.0f / 255.0f, 250.0f / 255.0f, 253.0f / 255.0f, 1.0f}, // selection/text
    {12.0f / 255.0f, 74.0f / 255.0f, 122.0f / 255.0f, 1.0f}, // graph/raster
    {82.0f / 255.0f, 56.0f / 255.0f, 116.0f / 255.0f, 1.0f}, // graph/compute
    {0.0f / 255.0f, 86.0f / 255.0f, 60.0f / 255.0f, 1.0f}, // graph/copy
    {111.0f / 255.0f, 54.0f / 255.0f, 0.0f / 255.0f, 1.0f}, // graph/external
    {91.0f / 255.0f, 68.0f / 255.0f, 4.0f / 255.0f, 1.0f}, // graph/group
    {97.0f / 255.0f, 64.0f / 255.0f, 6.0f / 255.0f, 1.0f}, // graph/sink
    {51.0f / 255.0f, 51.0f / 255.0f, 51.0f / 255.0f, 1.0f}, // graph/culled
    {121.0f / 255.0f, 176.0f / 255.0f, 232.0f / 255.0f, 1.0f}, // graph/link-0
    {220.0f / 255.0f, 154.0f / 255.0f, 108.0f / 255.0f, 1.0f}, // graph/link-1
    {124.0f / 255.0f, 189.0f / 255.0f, 137.0f / 255.0f, 1.0f}, // graph/link-2
    {190.0f / 255.0f, 170.0f / 255.0f, 94.0f / 255.0f, 1.0f}, // graph/link-3
    {80.0f / 255.0f, 191.0f / 255.0f, 190.0f / 255.0f, 1.0f}, // graph/link-4
    {227.0f / 255.0f, 145.0f / 255.0f, 145.0f / 255.0f, 1.0f}, // graph/link-5
    {170.0f / 255.0f, 160.0f / 255.0f, 230.0f / 255.0f, 1.0f}, // graph/link-6
    {185.0f / 255.0f, 172.0f / 255.0f, 95.0f / 255.0f, 1.0f}, // graph/link-7
    {76.0f / 255.0f, 171.0f / 255.0f, 253.0f / 255.0f, 1.0f}, // plot/line
    {212.0f / 255.0f, 152.0f / 255.0f, 36.0f / 255.0f, 1.0f}, // plot/limit
    {255.0f / 255.0f, 105.0f / 255.0f, 79.0f / 255.0f, 0.6f}, // overlay/bounds-candidate
    {255.0f / 255.0f, 219.0f / 255.0f, 79.0f / 255.0f, 0.9f}, // overlay/bounds-selected
    {76.0f / 255.0f, 171.0f / 255.0f, 253.0f / 255.0f, 1.0f}, // overlay/outline
    {255.0f / 255.0f, 240.0f / 255.0f, 181.0f / 255.0f, 1.0f}, // overlay/label
    {103.0f / 255.0f, 105.0f / 255.0f, 107.0f / 255.0f, 1.0f}, // console/trace
    {163.0f / 255.0f, 165.0f / 255.0f, 167.0f / 255.0f, 1.0f}, // console/debug
    {248.0f / 255.0f, 250.0f / 255.0f, 253.0f / 255.0f, 1.0f}, // console/info
    {212.0f / 255.0f, 152.0f / 255.0f, 36.0f / 255.0f, 1.0f}, // console/warn
    {249.0f / 255.0f, 119.0f / 255.0f, 114.0f / 255.0f, 1.0f}, // console/error
    {249.0f / 255.0f, 119.0f / 255.0f, 114.0f / 255.0f, 1.0f}, // console/critical
    {248.0f / 255.0f, 250.0f / 255.0f, 253.0f / 255.0f, 1.0f}, // overlay/text
}};

const ThemePalette kLightPalette = {{
    {222.0f / 255.0f, 224.0f / 255.0f, 226.0f / 255.0f, 1.0f}, // surface/canvas
    {255.0f / 255.0f, 255.0f / 255.0f, 255.0f / 255.0f, 1.0f}, // surface/panel
    {255.0f / 255.0f, 255.0f / 255.0f, 255.0f / 255.0f, 1.0f}, // surface/raised
    {242.0f / 255.0f, 244.0f / 255.0f, 246.0f / 255.0f, 1.0f}, // surface/sunken
    {233.0f / 255.0f, 235.0f / 255.0f, 238.0f / 255.0f, 1.0f}, // surface/hover
    {222.0f / 255.0f, 224.0f / 255.0f, 226.0f / 255.0f, 1.0f}, // surface/active
    {255.0f / 255.0f, 255.0f / 255.0f, 255.0f / 255.0f, 0.86f}, // surface/overlay
    {11.0f / 255.0f, 12.0f / 255.0f, 14.0f / 255.0f, 1.0f}, // surface/viewport
    {19.0f / 255.0f, 20.0f / 255.0f, 22.0f / 255.0f, 1.0f}, // text/primary
    {103.0f / 255.0f, 105.0f / 255.0f, 107.0f / 255.0f, 1.0f}, // text/secondary
    {132.0f / 255.0f, 134.0f / 255.0f, 136.0f / 255.0f, 1.0f}, // text/disabled
    {255.0f / 255.0f, 255.0f / 255.0f, 255.0f / 255.0f, 1.0f}, // text/on-accent
    {222.0f / 255.0f, 224.0f / 255.0f, 226.0f / 255.0f, 1.0f}, // border/subtle
    {132.0f / 255.0f, 134.0f / 255.0f, 136.0f / 255.0f, 1.0f}, // border/strong
    {5.0f / 255.0f, 111.0f / 255.0f, 184.0f / 255.0f, 1.0f}, // border/focus
    {5.0f / 255.0f, 111.0f / 255.0f, 184.0f / 255.0f, 1.0f}, // accent/operator
    {0.0f / 255.0f, 91.0f / 255.0f, 153.0f / 255.0f, 1.0f}, // accent/operator-hover
    {4.0f / 255.0f, 69.0f / 255.0f, 116.0f / 255.0f, 1.0f}, // accent/operator-active
    {0.0f / 255.0f, 91.0f / 255.0f, 153.0f / 255.0f, 1.0f}, // accent/operator-text
    {5.0f / 255.0f, 111.0f / 255.0f, 184.0f / 255.0f, 0.18f}, // accent/operator-subtle
    {126.0f / 255.0f, 79.0f / 255.0f, 183.0f / 255.0f, 1.0f}, // AccentAgent
    {106.0f / 255.0f, 58.0f / 255.0f, 160.0f / 255.0f, 1.0f}, // AccentAgentHover
    {80.0f / 255.0f, 44.0f / 255.0f, 122.0f / 255.0f, 1.0f}, // AccentAgentActive
    {106.0f / 255.0f, 58.0f / 255.0f, 160.0f / 255.0f, 1.0f}, // AccentAgentText
    {126.0f / 255.0f, 79.0f / 255.0f, 183.0f / 255.0f, 0.18f}, // AccentAgentSubtle
    {15.0f / 255.0f, 105.0f / 255.0f, 54.0f / 255.0f, 1.0f}, // status/success
    {117.0f / 255.0f, 80.0f / 255.0f, 0.0f / 255.0f, 1.0f}, // status/warning
    {158.0f / 255.0f, 34.0f / 255.0f, 40.0f / 255.0f, 1.0f}, // status/error
    {103.0f / 255.0f, 105.0f / 255.0f, 107.0f / 255.0f, 1.0f}, // status/info
    {5.0f / 255.0f, 111.0f / 255.0f, 184.0f / 255.0f, 1.0f}, // actor/operator
    {126.0f / 255.0f, 79.0f / 255.0f, 183.0f / 255.0f, 1.0f}, // ActorAgent
    {103.0f / 255.0f, 105.0f / 255.0f, 107.0f / 255.0f, 1.0f}, // actor/system
    {117.0f / 255.0f, 80.0f / 255.0f, 0.0f / 255.0f, 1.0f}, // prov/session
    {5.0f / 255.0f, 111.0f / 255.0f, 184.0f / 255.0f, 0.2f}, // selection/bg
    {19.0f / 255.0f, 20.0f / 255.0f, 22.0f / 255.0f, 1.0f}, // selection/text
    {197.0f / 255.0f, 226.0f / 255.0f, 253.0f / 255.0f, 1.0f}, // graph/raster
    {228.0f / 255.0f, 214.0f / 255.0f, 253.0f / 255.0f, 1.0f}, // graph/compute
    {193.0f / 255.0f, 233.0f / 255.0f, 214.0f / 255.0f, 1.0f}, // graph/copy
    {252.0f / 255.0f, 213.0f / 255.0f, 188.0f / 255.0f, 1.0f}, // graph/external
    {237.0f / 255.0f, 220.0f / 255.0f, 185.0f / 255.0f, 1.0f}, // graph/group
    {246.0f / 255.0f, 217.0f / 255.0f, 178.0f / 255.0f, 1.0f}, // graph/sink
    {209.0f / 255.0f, 209.0f / 255.0f, 209.0f / 255.0f, 1.0f}, // graph/culled
    {40.0f / 255.0f, 108.0f / 255.0f, 171.0f / 255.0f, 1.0f}, // graph/link-0
    {156.0f / 255.0f, 83.0f / 255.0f, 19.0f / 255.0f, 1.0f}, // graph/link-1
    {40.0f / 255.0f, 124.0f / 255.0f, 66.0f / 255.0f, 1.0f}, // graph/link-2
    {124.0f / 255.0f, 103.0f / 255.0f, 2.0f / 255.0f, 1.0f}, // graph/link-3
    {3.0f / 255.0f, 120.0f / 255.0f, 121.0f / 255.0f, 1.0f}, // graph/link-4
    {163.0f / 255.0f, 72.0f / 255.0f, 75.0f / 255.0f, 1.0f}, // graph/link-5
    {105.0f / 255.0f, 91.0f / 255.0f, 169.0f / 255.0f, 1.0f}, // graph/link-6
    {119.0f / 255.0f, 106.0f / 255.0f, 6.0f / 255.0f, 1.0f}, // graph/link-7
    {5.0f / 255.0f, 111.0f / 255.0f, 184.0f / 255.0f, 1.0f}, // plot/line
    {117.0f / 255.0f, 80.0f / 255.0f, 0.0f / 255.0f, 1.0f}, // plot/limit
    {255.0f / 255.0f, 105.0f / 255.0f, 79.0f / 255.0f, 0.6f}, // overlay/bounds-candidate
    {255.0f / 255.0f, 219.0f / 255.0f, 79.0f / 255.0f, 0.9f}, // overlay/bounds-selected
    {76.0f / 255.0f, 171.0f / 255.0f, 253.0f / 255.0f, 1.0f}, // overlay/outline
    {255.0f / 255.0f, 240.0f / 255.0f, 181.0f / 255.0f, 1.0f}, // overlay/label
    {132.0f / 255.0f, 134.0f / 255.0f, 136.0f / 255.0f, 1.0f}, // console/trace
    {103.0f / 255.0f, 105.0f / 255.0f, 107.0f / 255.0f, 1.0f}, // console/debug
    {19.0f / 255.0f, 20.0f / 255.0f, 22.0f / 255.0f, 1.0f}, // console/info
    {117.0f / 255.0f, 80.0f / 255.0f, 0.0f / 255.0f, 1.0f}, // console/warn
    {158.0f / 255.0f, 34.0f / 255.0f, 40.0f / 255.0f, 1.0f}, // console/error
    {158.0f / 255.0f, 34.0f / 255.0f, 40.0f / 255.0f, 1.0f}, // console/critical
    {248.0f / 255.0f, 250.0f / 255.0f, 253.0f / 255.0f, 1.0f}, // overlay/text
}};

const std::array<SlotRole, 63> kImGuiSlots = {{
    {"Text", ThemeRole::TextPrimary, 1.0f},
    {"TextDisabled", ThemeRole::TextDisabled, 1.0f},
    {"WindowBg", ThemeRole::SurfacePanel, 1.0f},
    {"ChildBg", ThemeRole::SurfacePanel, 0.0f},
    {"PopupBg", ThemeRole::SurfaceRaised, 1.0f},
    {"Border", ThemeRole::BorderSubtle, 1.0f},
    {"BorderShadow", ThemeRole::BorderSubtle, 0.0f},
    {"FrameBg", ThemeRole::SurfaceSunken, 1.0f},
    {"FrameBgHovered", ThemeRole::SurfaceHover, 1.0f},
    {"FrameBgActive", ThemeRole::SurfaceActive, 1.0f},
    {"TitleBg", ThemeRole::SurfaceCanvas, 1.0f},
    {"TitleBgActive", ThemeRole::SurfacePanel, 1.0f},
    {"TitleBgCollapsed", ThemeRole::SurfaceCanvas, 1.0f},
    {"MenuBarBg", ThemeRole::SurfacePanel, 1.0f},
    {"ScrollbarBg", ThemeRole::SurfaceCanvas, 1.0f},
    {"ScrollbarGrab", ThemeRole::BorderStrong, 1.0f},
    {"ScrollbarGrabHovered", ThemeRole::TextDisabled, 1.0f},
    {"ScrollbarGrabActive", ThemeRole::TextSecondary, 1.0f},
    {"CheckMark", ThemeRole::AccentOperator, 1.0f},
    {"CheckboxSelectedBg", ThemeRole::AccentOperatorSubtle, 1.0f},
    {"SliderGrab", ThemeRole::AccentOperator, 1.0f},
    {"SliderGrabActive", ThemeRole::AccentOperatorActive, 1.0f},
    {"Button", ThemeRole::SurfaceHover, 1.0f},
    {"ButtonHovered", ThemeRole::SurfaceActive, 1.0f},
    {"ButtonActive", ThemeRole::AccentOperatorSubtle, 1.0f},
    {"Header", ThemeRole::SelectionBg, 1.0f},
    {"HeaderHovered", ThemeRole::SurfaceHover, 1.0f},
    {"HeaderActive", ThemeRole::SurfaceActive, 1.0f},
    {"Separator", ThemeRole::BorderSubtle, 1.0f},
    {"SeparatorHovered", ThemeRole::BorderStrong, 1.0f},
    {"SeparatorActive", ThemeRole::AccentOperator, 1.0f},
    {"ResizeGrip", ThemeRole::BorderStrong, 1.0f},
    {"ResizeGripHovered", ThemeRole::AccentOperatorHover, 1.0f},
    {"ResizeGripActive", ThemeRole::AccentOperator, 1.0f},
    {"InputTextCursor", ThemeRole::TextPrimary, 1.0f},
    {"TabHovered", ThemeRole::SurfaceHover, 1.0f},
    {"Tab", ThemeRole::SurfaceCanvas, 1.0f},
    {"TabSelected", ThemeRole::SurfacePanel, 1.0f},
    {"TabSelectedOverline", ThemeRole::AccentOperator, 1.0f},
    {"TabDimmed", ThemeRole::SurfaceCanvas, 1.0f},
    {"TabDimmedSelected", ThemeRole::SurfacePanel, 1.0f},
    {"TabDimmedSelectedOverline", ThemeRole::BorderStrong, 1.0f},
    {"DockingPreview", ThemeRole::AccentOperatorSubtle, 1.0f},
    {"DockingEmptyBg", ThemeRole::SurfaceCanvas, 1.0f},
    {"PlotLines", ThemeRole::AccentOperator, 1.0f},
    {"PlotLinesHovered", ThemeRole::AccentOperatorHover, 1.0f},
    {"PlotHistogram", ThemeRole::AccentOperator, 1.0f},
    {"PlotHistogramHovered", ThemeRole::AccentOperatorHover, 1.0f},
    {"TableHeaderBg", ThemeRole::SurfaceCanvas, 1.0f},
    {"TableBorderStrong", ThemeRole::BorderStrong, 1.0f},
    {"TableBorderLight", ThemeRole::BorderSubtle, 1.0f},
    {"TableRowBg", ThemeRole::SurfacePanel, 0.0f},
    {"TableRowBgAlt", ThemeRole::SurfaceHover, 0.35f},
    {"TextLink", ThemeRole::AccentOperatorText, 1.0f},
    {"TextSelectedBg", ThemeRole::SelectionBg, 1.0f},
    {"TreeLines", ThemeRole::BorderSubtle, 1.0f},
    {"DragDropTarget", ThemeRole::AccentOperator, 1.0f},
    {"DragDropTargetBg", ThemeRole::AccentOperatorSubtle, 1.0f},
    {"UnsavedMarker", ThemeRole::ActorOperator, 1.0f},
    {"NavCursor", ThemeRole::AccentOperator, 1.0f},
    {"NavWindowingHighlight", ThemeRole::AccentOperator, 1.0f},
    {"NavWindowingDimBg", ThemeRole::SurfaceCanvas, 0.6f},
    {"ModalWindowDimBg", ThemeRole::SurfaceCanvas, 0.6f},
}};

const std::array<SlotRole, 19> kNodeEditorSlots = {{
    {"Bg", ThemeRole::SurfaceCanvas, 1.0f},
    {"Grid", ThemeRole::BorderSubtle, 1.0f},
    {"NodeBg", ThemeRole::SurfaceRaised, 1.0f},
    {"NodeBorder", ThemeRole::BorderSubtle, 1.0f},
    {"HoveredNodeBorder", ThemeRole::AccentOperatorHover, 1.0f},
    {"SelNodeBorder", ThemeRole::AccentOperator, 1.0f},
    {"NodeSelRect", ThemeRole::AccentOperatorSubtle, 1.0f},
    {"NodeSelRectBorder", ThemeRole::AccentOperator, 1.0f},
    {"HoveredLinkBorder", ThemeRole::AccentOperatorHover, 1.0f},
    {"SelLinkBorder", ThemeRole::AccentOperator, 1.0f},
    {"HighlightLinkBorder", ThemeRole::AccentOperatorActive, 1.0f},
    {"LinkSelRect", ThemeRole::AccentOperatorSubtle, 1.0f},
    {"LinkSelRectBorder", ThemeRole::AccentOperator, 1.0f},
    {"PinRect", ThemeRole::AccentOperatorSubtle, 1.0f},
    {"PinRectBorder", ThemeRole::AccentOperator, 1.0f},
    {"Flow", ThemeRole::AccentOperator, 1.0f},
    {"FlowMarker", ThemeRole::AccentOperator, 1.0f},
    {"GroupBg", ThemeRole::SurfacePanel, 0.5f},
    {"GroupBorder", ThemeRole::BorderSubtle, 1.0f},
}};

const std::array<ContrastPair, 24> kDarkContrastPairs = {{
    {"text/primary on surface/panel",
     ThemeRole::TextPrimary, ThemeRole::SurfacePanel, std::nullopt, 4.5},
    {"text/secondary on surface/panel",
     ThemeRole::TextSecondary, ThemeRole::SurfacePanel, std::nullopt, 4.5},
    {"text/primary on surface/raised",
     ThemeRole::TextPrimary, ThemeRole::SurfaceRaised, std::nullopt, 4.5},
    {"text/secondary on surface/raised",
     ThemeRole::TextSecondary, ThemeRole::SurfaceRaised, std::nullopt, 4.5},
    {"text/primary on surface/sunken",
     ThemeRole::TextPrimary, ThemeRole::SurfaceSunken, std::nullopt, 4.5},
    {"text/secondary on surface/sunken",
     ThemeRole::TextSecondary, ThemeRole::SurfaceSunken, std::nullopt, 4.5},
    {"text/primary on surface/hover",
     ThemeRole::TextPrimary, ThemeRole::SurfaceHover, std::nullopt, 4.5},
    {"text/secondary on surface/hover",
     ThemeRole::TextSecondary, ThemeRole::SurfaceHover, std::nullopt, 4.5},
    {"text/disabled on surface/panel",
     ThemeRole::TextDisabled, ThemeRole::SurfacePanel, std::nullopt, 3.0},
    {"accent/operator-text on surface/panel",
     ThemeRole::AccentOperatorText, ThemeRole::SurfacePanel, std::nullopt, 4.5},
    {"AccentAgentText on surface/panel",
     ThemeRole::AccentAgentText, ThemeRole::SurfacePanel, std::nullopt, 4.5},
    {"status/success on surface/panel",
     ThemeRole::StatusSuccess, ThemeRole::SurfacePanel, std::nullopt, 4.5},
    {"status/warning on surface/panel",
     ThemeRole::StatusWarning, ThemeRole::SurfacePanel, std::nullopt, 4.5},
    {"status/error on surface/panel",
     ThemeRole::StatusError, ThemeRole::SurfacePanel, std::nullopt, 4.5},
    {"text/on-accent on accent/operator",
     ThemeRole::TextOnAccent, ThemeRole::AccentOperator, std::nullopt, 4.5},
    {"text/on-accent on AccentAgent",
     ThemeRole::TextOnAccent, ThemeRole::AccentAgent, std::nullopt, 4.5},
    {"accent/operator on surface/panel",
     ThemeRole::AccentOperator, ThemeRole::SurfacePanel, std::nullopt, 3.0},
    {"AccentAgent on surface/panel",
     ThemeRole::AccentAgent, ThemeRole::SurfacePanel, std::nullopt, 3.0},
    {"border/strong on surface/panel",
     ThemeRole::BorderStrong, ThemeRole::SurfacePanel, std::nullopt, 3.0},
    {"panel/canvas island floor",
     ThemeRole::SurfacePanel, ThemeRole::SurfaceCanvas, std::nullopt, 1.1},
    {"subtle/panel hairline",
     ThemeRole::BorderSubtle, ThemeRole::SurfacePanel, std::nullopt, 1.1},
    {"overlay/text on surface/viewport",
     ThemeRole::OverlayText, ThemeRole::SurfaceViewport, std::nullopt, 4.5},
    {"text/primary on selection (composited)",
     ThemeRole::TextPrimary, ThemeRole::SelectionBg, ThemeRole::SurfacePanel, 4.5},
    {"prov/session on surface/panel",
     ThemeRole::ProvSession, ThemeRole::SurfacePanel, std::nullopt, 4.5},
}};

const std::array<ContrastPair, 24> kLightContrastPairs = {{
    {"text/primary on surface/panel",
     ThemeRole::TextPrimary, ThemeRole::SurfacePanel, std::nullopt, 4.5},
    {"text/secondary on surface/panel",
     ThemeRole::TextSecondary, ThemeRole::SurfacePanel, std::nullopt, 4.5},
    {"text/primary on surface/raised",
     ThemeRole::TextPrimary, ThemeRole::SurfaceRaised, std::nullopt, 4.5},
    {"text/secondary on surface/raised",
     ThemeRole::TextSecondary, ThemeRole::SurfaceRaised, std::nullopt, 4.5},
    {"text/primary on surface/sunken",
     ThemeRole::TextPrimary, ThemeRole::SurfaceSunken, std::nullopt, 4.5},
    {"text/secondary on surface/sunken",
     ThemeRole::TextSecondary, ThemeRole::SurfaceSunken, std::nullopt, 4.5},
    {"text/primary on surface/hover",
     ThemeRole::TextPrimary, ThemeRole::SurfaceHover, std::nullopt, 4.5},
    {"text/secondary on surface/hover",
     ThemeRole::TextSecondary, ThemeRole::SurfaceHover, std::nullopt, 4.5},
    {"text/disabled on surface/panel",
     ThemeRole::TextDisabled, ThemeRole::SurfacePanel, std::nullopt, 3.0},
    {"accent/operator-text on surface/panel",
     ThemeRole::AccentOperatorText, ThemeRole::SurfacePanel, std::nullopt, 4.5},
    {"AccentAgentText on surface/panel",
     ThemeRole::AccentAgentText, ThemeRole::SurfacePanel, std::nullopt, 4.5},
    {"status/success on surface/panel",
     ThemeRole::StatusSuccess, ThemeRole::SurfacePanel, std::nullopt, 4.5},
    {"status/warning on surface/panel",
     ThemeRole::StatusWarning, ThemeRole::SurfacePanel, std::nullopt, 4.5},
    {"status/error on surface/panel",
     ThemeRole::StatusError, ThemeRole::SurfacePanel, std::nullopt, 4.5},
    {"text/on-accent on accent/operator",
     ThemeRole::TextOnAccent, ThemeRole::AccentOperator, std::nullopt, 4.5},
    {"text/on-accent on AccentAgent",
     ThemeRole::TextOnAccent, ThemeRole::AccentAgent, std::nullopt, 4.5},
    {"accent/operator on surface/panel",
     ThemeRole::AccentOperator, ThemeRole::SurfacePanel, std::nullopt, 3.0},
    {"AccentAgent on surface/panel",
     ThemeRole::AccentAgent, ThemeRole::SurfacePanel, std::nullopt, 3.0},
    {"border/strong on surface/panel",
     ThemeRole::BorderStrong, ThemeRole::SurfacePanel, std::nullopt, 3.0},
    {"panel/canvas island floor",
     ThemeRole::SurfacePanel, ThemeRole::SurfaceCanvas, std::nullopt, 1.2},
    {"subtle/panel hairline",
     ThemeRole::BorderSubtle, ThemeRole::SurfacePanel, std::nullopt, 1.1},
    {"overlay/text on surface/viewport",
     ThemeRole::OverlayText, ThemeRole::SurfaceViewport, std::nullopt, 4.5},
    {"text/primary on selection (composited)",
     ThemeRole::TextPrimary, ThemeRole::SelectionBg, ThemeRole::SurfacePanel, 4.5},
    {"prov/session on surface/panel",
     ThemeRole::ProvSession, ThemeRole::SurfacePanel, std::nullopt, 4.5},
}};

// clang-format on

} // namespace lmx::app
