//----------------------------------------------------------------------------------------------------------------------
/// @file Provenance.cpp
/// @brief Builds owned source descriptions for document, subject, and resolution provenance.
//----------------------------------------------------------------------------------------------------------------------
#include "App/Model/Workspace/Provenance.h"

#include <format>
#include <utility>

namespace lmx::app {
namespace {

//======================================================================================================================
std::string generatedSentence(std::string_view generator) {
    return std::format("Generated by {} · not saved", generator);
}

} // namespace

//======================================================================================================================
std::optional<ProvenanceMark> documentProvenance(bool dirty, std::string_view path) {
    if (!dirty)
        return std::nullopt;
    return ProvenanceMark{Provenance::Edited, Actor::Operator,
                          std::format("Unsaved operator edits · {}", path)};
}

//======================================================================================================================
ProvenanceMark proposedProvenance(std::string_view client) {
    const bool unknown = client.empty() || client == "Unknown external change";
    return ProvenanceMark{
        Provenance::Proposed, unknown ? Actor::System : Actor::Agent,
        std::format("Pending scene proposal · {}", unknown ? "Unknown external change" : client)};
}

//======================================================================================================================
ProvenanceMark sessionAppliedProvenance(std::string_view client) {
    return {Provenance::AgentApplied, Actor::Agent,
            std::format("Applied by {}", client.empty() ? "Agent" : client)};
}

//======================================================================================================================
std::optional<ProvenanceMark> subjectProvenance(std::optional<std::string_view> generatedBy,
                                                std::optional<std::string_view> cliFlag,
                                                bool edited) {
    if (generatedBy || cliFlag) {
        std::string source;
        if (generatedBy)
            source = generatedSentence(*generatedBy);
        if (cliFlag) {
            if (!source.empty())
                source += " · ";
            source += std::format("CLI mask {}", *cliFlag);
            if (!generatedBy)
                source += " · not saved";
        }
        if (edited)
            source += " · edited by operator";
        return ProvenanceMark{Provenance::SessionOnly,
                              edited || cliFlag ? Actor::Operator : Actor::System,
                              std::move(source)};
    }
    if (edited)
        return ProvenanceMark{Provenance::Edited, Actor::Operator, "Operator edit"};
    return std::nullopt;
}

//======================================================================================================================
std::string rowProvenanceTooltip(std::optional<std::string_view> generatedBy,
                                 const std::optional<ProvenanceMark>& mark) {
    std::string tip;
    if (generatedBy) {
        const std::string sentence = generatedSentence(*generatedBy);
        if (!mark || !mark->source.starts_with(sentence))
            tip = sentence;
    }
    if (mark) {
        if (!tip.empty())
            tip += "\n";
        tip += mark->source;
    }
    return tip;
}

//======================================================================================================================
std::optional<ProvenanceMark> resolutionProvenance(bool controllerOn, float scale, float budgetMs) {
    if (!controllerOn)
        return std::nullopt;
    return ProvenanceMark{
        Provenance::SystemApplied, Actor::System,
        std::format("Dynamic resolution · scale {:.3f} · GPU budget {:.2f} ms", scale, budgetMs)};
}

} // namespace lmx::app
