//----------------------------------------------------------------------------------------------------------------------
/// @file Provenance.cpp
/// @brief Builds owned source descriptions for document, subject, and resolution provenance.
//----------------------------------------------------------------------------------------------------------------------
#include "App/Model/Workspace/Provenance.h"

#include <format>
#include <utility>

namespace lmx::app {

//======================================================================================================================
std::optional<ProvenanceMark> documentProvenance(bool dirty, std::string_view path) {
    if (!dirty)
        return std::nullopt;
    return ProvenanceMark{Provenance::Edited, Actor::Operator,
                          std::format("Unsaved operator edits · {}", path)};
}

//======================================================================================================================
std::optional<ProvenanceMark> subjectProvenance(std::optional<std::string_view> generatedBy,
                                                std::optional<std::string_view> cliFlag,
                                                bool edited) {
    if (generatedBy || cliFlag) {
        std::string source;
        if (generatedBy)
            source = std::format("Generated by {} · not saved", *generatedBy);
        if (cliFlag) {
            if (!source.empty())
                source += " · ";
            source += std::format("CLI mask {}", *cliFlag);
            if (!generatedBy)
                source += " · not saved";
        }
        if (edited)
            source += " · edited by operator";
        return ProvenanceMark{Provenance::SessionOnly,
                              edited || cliFlag ? Actor::Operator : Actor::System,
                              std::move(source)};
    }
    if (edited)
        return ProvenanceMark{Provenance::Edited, Actor::Operator, "Operator edit"};
    return std::nullopt;
}

//======================================================================================================================
std::optional<ProvenanceMark> resolutionProvenance(bool controllerOn, float scale, float budgetMs) {
    if (!controllerOn)
        return std::nullopt;
    return ProvenanceMark{
        Provenance::SystemApplied, Actor::System,
        std::format("Dynamic resolution · scale {:.3f} · GPU budget {:.2f} ms", scale, budgetMs)};
}

} // namespace lmx::app
