//----------------------------------------------------------------------------------------------------------------------
/// @file InspectorObject.cpp
/// @brief Implements the Inspector panel's object controls and visibility readings.
//----------------------------------------------------------------------------------------------------------------------

#include "App/Panels/Inspector/InspectorInternal.h"

#include "App/Model/Scene/InspectorSubject.h"
#include "App/Panels/Shared/EditorStyle.h"

#include <imgui.h>

#include <algorithm>
#include <string>

namespace lmx::app {

//======================================================================================================================
void drawObjectSection(const InspectorPanelContext& context, size_t index) {
    auto& session = context.session;
    auto& object = session.scene().objects[index];
    const auto enabledState = inspectorEnabledState(session, context.selection);
    if (!enabledState) {
        editor_style::message("This object no longer exists in the active document.", true);
        return;
    }
    const bool animated =
        std::ranges::any_of(session.scene().animation.tracks,
                            [index](const auto& track) { return track.objectIndex == index; });
    bool enabled = enabledState->own;
    if (drawInspectorHeader(enabledState->label.c_str(), enabledState->kind.c_str(),
                            "Restore this object's authored transform and own enabled state. "
                            "Animated objects use their track at the current time.",
                            session.objectChanged(index) ||
                                enabledState->own != enabledState->baseline,
                            &enabled)) {
        session.resetObject(index);
        if (const auto result = resetInspectorEnabled(session, context.selection); !result)
            editor_style::message(result.error().message.c_str(), true);
        requestCameraCut(context.temporalState);
    } else if (enabled != enabledState->own) {
        if (const auto result = setInspectorEnabled(session, context.selection, enabled); !result)
            editor_style::message(result.error().message.c_str(), true);
        else
            requestCameraCut(context.temporalState);
    }
    if (!enabledState->generatedBy.empty()) {
        const std::string marker = "Generated by " + enabledState->generatedBy + " · not saved";
        editor_style::message(marker.c_str());
    }
    if (enabledState->own && !enabledState->effective)
        editor_style::message("Off in scene because an ancestor is disabled.");
    if (enabledState->primitiveCount > 1)
        ImGui::TextDisabled("One source node controls all %zu material primitives.",
                            enabledState->primitiveCount);
    const auto visibilityFields = context.visibilityDisplay == nullptr
                                      ? objectVisibilityFields(nullptr)
                                      : context.visibilityDisplay->objectFields(
                                            object.id, context.temporalState.sceneGeneration);
    const auto diagnostic = [](const VisibilityField& row) {
        return row.label != "Visibility" && row.label != "Reason" &&
               row.label != "Occlusion outcome";
    };
    if (editor_style::beginPropertyGrid("objectFields")) {
        DecomposedTransform transform{object.position, object.eulerDegrees, object.scale};
        bool edited =
            editor_style::vector3("Position (world)", "position", &transform.position.x, 0.05f);
        if (animated)
            editorTooltip("Pause playback to edit. Reset samples the authored track at the current "
                          "time; playback replaces transform edits on its next sample.");
        edited |= editor_style::vector3("Rotation (XYZ degrees)", "rotation",
                                        &transform.eulerDegrees.x, 1.0f);
        edited |= editor_style::vector3("Scale", "scale", &transform.scale.x, 0.01f, 0.01f, 100.0f,
                                        "%.3f", ImGuiSliderFlags_AlwaysClamp);
        if (edited) {
            session.editObject(index, transform);
            requestCameraCut(context.temporalState);
        }
        for (const auto& row : visibilityFields) {
            if (!diagnostic(row))
                valueRow(row.label.c_str(), row.value);
        }
        editor_style::endFields();
    }
    if (editor_style::beginDiagnostics()) {
        if (editor_style::beginPropertyGrid("objectDiagnostics")) {
            valueRow("Mesh row", std::to_string(object.mesh.slot));
            valueRow("Material row", std::to_string(object.material.slot));
            for (const auto& row : visibilityFields) {
                if (diagnostic(row))
                    valueRow(row.label.c_str(), row.value);
            }
            editor_style::endFields();
        }
        editor_style::endDiagnostics();
    }
}

} // namespace lmx::app
