-- CPU decoding and generation share descriptor vocabulary without linking GPU interfaces.
target("Asset")
    set_kind("static")
    add_files("*.cpp", "Image/*.cpp", "Model/*.cpp", "Texture/*.cpp")
    add_files("Document/SceneDocumentRead.cpp", "Document/SceneDocumentWrite.cpp")
    add_files("Document/SceneDocumentContentWrite.cpp", "Document/SceneDocumentSave.cpp")
    add_files("Document/SceneDocumentDiff.cpp")
    add_files("Document/DocumentUri.cpp")
    add_files("Document/Orientation.cpp", {cxxflags = "-ffp-contract=off"})
    add_deps("Core")
    add_includedirs("../../../RojoRHI/Include", {public = true})
    add_packages("cgltf", "stb")
